version: '3.0'
services:
  web:
      build: .
      container_name: challenge_web
      command: >
        sh -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
      volumes:
        - .:/code
      restart: on-failure
      ports:
        - "8000:8000"
      depends_on:
        - db
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    hostname: postgres
    container_name: challenge_db
    environment:
      POSTGRES_PASSWORD: "challenge"
      POSTGRES_DB: "challenge"
      POSTGRES_USER: "postgres"
